name: EconomyBlocks
version: '${project.version}'
main: craftplugins.economyblocks.EconomyBlocks
api-version: 1.19
authors: [ Dirk ]
description: Custom Minecraft economy plugin with buying "Lucky Block" care packages
commands:
  send:
    description: Send money to other people
  carepackage:
    description: Open the care package GUI
    aliases:
      - cp
      - cpshop
      - carepackageshop
  balance:
    aliases:
      - bal
    description: Gets the player's current account balance
  shop:
    description: Open the mineral shop GUI