name: EconomyBlocks
version: '${project.version}'
main: craftplugins.economyblocks.EconomyBlocks
api-version: 1.19
authors: [ Dirk ]
description: Custom Minecraft economy plugin with buying "Lucky Block" care packages
commands:
  send:
    description: Send money to other people
    usage: /send {username} {amount}

  buy:
    description: Open the buy shop

  balance:
    aliases:
      - bal
    description: Gets the player's current account balance

  sell:
    description: Open the sell shop

  go:
    description: Open teleport GUI

  godisable:
    description: Disable teleporting to you

  goenable:
    description: Enable teleporting to you

  sethome:
    description: Set your home
    aliases:
      - sh

  homes:
    description: Display your home location
    aliases:
      - h

  info:
    description: Displayed information about the plugin
    aliases:
      - commands

  hub:
    description: Goes to hub

  community:
    description: Community commands
    aliases:
      - c

  fbs:
    description: Open the Fill Block Shop menu
    aliases:
      - fillblockshop
      - fbshop

  shop:
    description: Opens the shops menu
    aliases:
      - shops

  setbal:
    description: Allows the console to set a player's balance

  colors:
    description: Displays possible chat colors

  nick:
    description: Changes nickname